chatbot:
  # Deployment name
  name: chatbot-api

  # Deployment image
  image:
    name: ghcr.io/basedosdados/chatbot
    tag: ""
    pullPolicy: Always

  # Number of replicas
  replicas: 1

  # Resource specification
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 2Gi

  # Required: name of the Secret containing chatbot-specific
  # environment variables (e.g., chatbot-api-prod-secrets)
  envSecret: ""

  # Required: name of the shared Secret from basedosdados-api
  # containing Django Secret Key (e.g., api-prod-secrets)
  sharedEnvSecret: ""
