apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.chatbot.name }}-migration"
  labels:
    app.kubernetes.io/component: basedosdados-chatbot
    app.kubernetes.io/name: "{{ .Values.chatbot.name }}-migration"
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: basedosdados-chatbot
        app.kubernetes.io/name: "{{ .Values.chatbot.name }}-migration"
    spec:
      containers:
        - name: basedosdados-chatbot-migration
          image: "{{ .Values.chatbot.image.name }}:{{ .Values.chatbot.image.tag }}"
          imagePullPolicy: {{ .Values.chatbot.image.pullPolicy }}
          command: ["alembic", "upgrade", "head"]
          env:
            - name: PG_HOST
              value: {{ .Values.chatbot.sharedDatabase.host | quote }}
            - name: PG_PORT
              value: {{ .Values.chatbot.sharedDatabase.port | quote }}
            - name: PG_USER
              value: {{ .Values.chatbot.sharedDatabase.user | quote }}
            - name: PG_DB
              value: {{ .Values.chatbot.sharedDatabase.name | quote }}
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.chatbot.sharedDatabase.passwordSecret | quote }}
                  key: password
          envFrom:
            - secretRef:
                name: {{ .Values.chatbot.envSecret | quote }}
      restartPolicy: Never
  backoffLimit: 3
