apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.chatbot.name }}-migration"
  labels:
    app.kubernetes.io/component: basedosdados-chatbot
    app.kubernetes.io/name: "{{ .Values.chatbot.name }}-migration"
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: basedosdados-chatbot
        app.kubernetes.io/name: "{{ .Values.chatbot.name }}-migration"
    spec:
      containers:
        - name: basedosdados-chatbot-migration
          image: "{{ .Values.chatbot.image.name }}:{{ .Values.chatbot.image.tag }}"
          imagePullPolicy: {{ .Values.chatbot.image.pullPolicy }}
          command: ["alembic", "upgrade", "head"]
          env:
            - name: JWT_ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.chatbot.envSharedSecret | quote }}
                  key: DJANGO_JWT_ALGORITHM
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.chatbot.envSharedSecret | quote }}
                  key: DJANGO_SECRET_KEY
          envFrom:
            - configMapRef:
                name: {{ .Values.chatbot.envConfigMap | quote }}
            - secretRef:
                name: {{ .Values.chatbot.envSecret | quote }}
      restartPolicy: Never
  activeDeadlineSeconds: 300
  backoffLimit: 3
