apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.chatbot.name }}-service"
  labels:
    app.kubernetes.io/component: basedosdados-chatbot
    app.kubernetes.io/name: {{ .Values.chatbot.name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: basedosdados-chatbot
    app.kubernetes.io/name: {{ .Values.chatbot.name }}
  ports:
    - name: http
      port: 80
      targetPort: fastapi
