name: Test Helm

on:
  pull_request:
    paths: ["charts/**"]
  # Allow manual execution from the Actions tab
  workflow_dispatch:

jobs:
  test-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v4.0.0

      - name: Lint Helm chart
        run: |
          cat << EOF | helm lint charts/basedosdados-chatbot --values -
          chatbot:
            image:
              tag: test
            envConfigMap: test-configmap
            envSecret: test-secret
            envSharedSecret: test-shared-secret
          EOF

      - name: Validate Helm template
        run: |
          cat << EOF | helm template test-release charts/basedosdados-chatbot --values -
          chatbot:
            image:
              tag: test
            envConfigMap: test-configmap
            envSecret: test-secret
            envSharedSecret: test-shared-secret
          EOF
